# Generated by Django 4.2.11 on 2024-03-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_it_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_name_secondary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
