# Generated by Django 4.2.11 on 2024-03-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_it_app', '0003_alter_user_date_of_birth_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
