# Generated by Django 4.2.11 on 2024-03-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_it_app', '0004_listings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='from_unregistered_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
