# Generated by Django 4.2.11 on 2024-03-10 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell_it_app', '0005_messages_from_unregistered_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
