# Generated by Django 4.2.11 on 2024-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_it_app', '0006_alter_messages_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread'),
        ),
    ]
