# Generated by Django 4.2.11 on 2024-03-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_it_app', '0007_messages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
