# Generated by Django 4.2.11 on 2024-03-11 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_it_app', '0009_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='avatar',
            field=models.ImageField(upload_to='uploads/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
