# Generated by Django 4.2.11 on 2024-03-13 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_it_app', '0010_alter_avatars_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='listings',
            field=models.ManyToManyField(to='sell_it_app.listings'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='offer_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Buy', 'Buy'), ('For Free', 'For free')], default='Sell', max_length=20),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='uploads/listing_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
