# Generated by Django 4.2.11 on 2024-03-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_it_app', '0011_address_listings_alter_listings_offer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
