# Generated by Django 4.2.11 on 2024-03-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell_it_app', '0012_alter_listings_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='listings',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='listings',
            name='address_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sell_it_app.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='picture_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='sell_it_app.picture'),
            preserve_default=False,
        ),
    ]
