# Generated by Django 4.2.11 on 2024-03-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell_it_app', '0014_remove_listings_picture_id_picture_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='sell_it_app.listings'),
        ),
    ]
